name: example
description: Example project for json_factory_generator.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  json_factory_annotation: 1.0.0

dev_dependencies:
  json_serializable: ^6.10.0
  build_runner: ^2.7.0
  test: ^1.26.3
  json_factory_generator: 1.0.0
