name: example
description: Example project for json_factory_generator.
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  json_factory_generator:
    path: ../

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.0
