name: example
description: Example project for json_factory_generator.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  json_factory_generator:
    path: ../

dev_dependencies:
  build_runner: ^2.7.0
  test: ^1.26.3
