name: json_factory_generator
description: A code generator that creates centralized, type-safe JSON factories for Dart models with support for single objects and List<T> parsing.
version: 0.1.3
homepage: https://github.com/thang-duong/json_factory_generator
repository: https://github.com/thang-duong/json_factory_generator

environment:
  sdk: ">=3.5.2 <4.0.0"

platforms:
  linux:
  macos:
  windows:

dependencies:
  build: ^3.0.2
  source_gen: ^3.1.0
  analyzer: '>=7.4.0 <9.0.0'
  glob: ^2.1.3
  meta: ^1.15.0

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.7.0
  build_test: ^3.3.2
  test: ^1.26.3
