name: json_factory_generator
description: A code generator that creates centralized, type-safe JSON factories for Dart models. Automatically discovers @jsonModel classes and generates a JsonFactory with support for both single objects and List<T> parsing.
version: 0.1.2
homepage: https://github.com/thang-duong/json_factory_generator
repository: https://github.com/thang-duong/json_factory_generator

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  build: ^2.4.0
  source_gen: ^1.4.0
  analyzer: ^5.13.0
  glob: ^2.1.0
  meta: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.0
  build_test: ^2.2.0
  test: ^1.24.0
  json_serializable: ^6.7.0
