name: json_factory_generator
description: A code generator for automatically creating and registering JSON factory methods in Dart models.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  build: ^2.4.2
  source_gen: ^1.5.0
  analyzer: ^6.7.0
  glob: ^2.1.2
  meta: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.6
  build_test: ^2.2.1
  test: ^1.24.0
  json_serializable: ^6.7.1
