name: json_factory_annotation
# Centralized, type-safe JSON factory annotation for Dart models
# -------------------------------------------------------------
description: Annotation for centralized, type-safe JSON factory generation in Dart models. Supports generic API responses and complex object graphs.
version: 1.0.1
homepage: https://pub.dev/packages/json_factory_annotation
repository: https://github.com/thang-duong/json_factory_generator
# Documentation: https://github.com/thang-duong/json_factory_generator/blob/main/README.md
# Issue Tracker: https://github.com/thang-duong/json_factory_generator/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.15.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
